### ISSUE TITLE
Error with template, not rendering

### ISSUE THREAD

**Issue by superxpro12** [timothycrosley/GuiBuilder#7]
Stack Trace:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/GuiBuilder/GuiBuilder.py", line 738, in updatePreview
    self.ui.preview.setHtml(self.html(element.toHTML()), QUrl.fromLocalFile(sharedFilesRoot + "/"))
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Layout.py", line 192, in toHTML
    returnValue = Box.toHTML(self, formatted=formatted, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1414, in toHTML
    data = (self.startTag() or '', self.content(formatted, _args, *_kwargs), self.endTag() or '')
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1280, in content
    elements = [element.toHTML(formatted=formatted, _args, *_kwargs) for element in self.childElements]
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1414, in toHTML
    data = (self.startTag() or '', self.content(formatted, _args, *_kwargs), self.endTag() or '')
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1280, in content
    elements = [element.toHTML(formatted=formatted, _args, *_kwargs) for element in self.childElements]
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1414, in toHTML
    data = (self.startTag() or '', self.content(formatted, _args, *_kwargs), self.endTag() or '')
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1280, in content
    elements = [element.toHTML(formatted=formatted, _args, *_kwargs) for element in self.childElements]
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1414, in toHTML
    data = (self.startTag() or '', self.content(formatted, _args, *_kwargs), self.endTag() or '')
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1280, in content
    elements = [element.toHTML(formatted=formatted, _args, *_kwargs) for element in self.childElements]
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Base.py", line 1412, in toHTML
    self._render()
  File "/usr/local/lib/python2.7/dist-packages/WebElements/Layout.py", line 393, in _render
    columns[columnIndex].addChildElement(element, ensureUnique=False, style=style)
TypeError: addChildElement() got an unexpected keyword argument 'style'

Template:
fields
 center
  grid numberOfColumns=2
   vertical
    > label#titlelabel text=Title
    > textarea#title width=0
    horizontal
     vertical
      > label#daylabel text=Day
      > select#daydropdown width=40 height=40
     vertical
      > label#monthlabel text=Month
      > select#monthdropdown width=40
     vertical
      > label#yearlabel text="Year      "
      > select#yeardropdown width=40
    > label#postlabel text=Post
    > textarea#postcontent
    > button#postbutton width=0 text=Post

> vertical

**Comment by timothycrosley** [comment]
Issue has been verified, is caused by a Bug in the WebElements Grid layout - will have a fix patched with the next release
